# Generated by Django 5.1.7 on 2025-03-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
