# Generated by Django 5.1.7 on 2025-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0002_alter_payment_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
    ]
