# Generated by Django 5.1.7 on 2025-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0003_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
    ]
