# Generated by Django 5.1.7 on 2025-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0004_paymentrequest_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="origin",
            field=models.CharField(
                choices=[("direct", "Direct Payment"), ("request", "Payment Request")],
                default="direct",
                max_length=10,
            ),
        ),
    ]
