# Generated by Django 5.1.7 on 2025-03-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0005_payment_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="original_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="original_currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
    ]
