# Generated by Django 5.1.7 on 2025-03-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0006_payment_original_amount_payment_original_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
