# Generated by Django 5.1.7 on 2025-04-04 17:04

import thrift_client
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0007_payment_read_status_paymentrequest_read_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(default=thrift_client.get_timestamp),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="timestamp",
            field=models.DateTimeField(default=thrift_client.get_timestamp),
        ),
    ]
